### ISSUE TITLE
--pH argument not working anymore?

### ISSUE THREAD

**Issue by naeemmrz** [forlilab/Meeko#11]
Hello,
I was recently following the new AutoDock Vina's examples at https://autodock-vina.readthedocs.io/en/latest/docking_basic.html and under the Ligand preparation section, they've used the mk_prepare_ligand.py as
`$ mk_prepare_ligand.py -i 1iep_ligand.sdf -o 1iep_ligand.pdbqt --pH 7.4`

However, when I tried the same I was prompted with the following error: 
`mk_prepare_ligand.py: error: unrecognized arguments: --pH 7.4`

Is there something I'm missing or is this feature no more?

Thanks :)

**Comment by diogomart** [comment]
Hello,

We dropped the pH feature since v0.3.0. Maybe we should have announced this change more loudly, in the README perhaps.

Part of the reason is the migration from OpenBabel to RDKit: the latter does not have a set of transformations for pH adjustments like OpenBabel does (at least that I know of). 

We will add a pH feature option to our ligand preparation tools in the future. Users can still use OpenBabel prior to Meeko for pH correction, although there are some known bugs related to the pH transformation: https://github.com/openbabel/openbabel/issues/2441, https://github.com/openbabel/openbabel/issues/2284
