### ISSUE TITLE
Remove coords from MoleculeSetups in Meeko

### ISSUE THREAD

**Issue by psharma-sr** [forlilab/Meeko#143]
Evaluate if coords can be eliminated from MoleculeSetups and remove them if possible.

**Comment by diogomart** [comment]
@mallanos and @mattholc weren't as enthusiastic about this as me and @nbruciaferri, so we decided to not separate the coordinates from the molsetups, unless it really is necessary to address #131

**Comment by diogomart** [comment]
Arguments in favor of separating coords from molsetups:
 - similarity to the design of openmm (topology and positions are separate) and RDKit (conformer objects are option in molecule objects)
 - docking results are small trajectories
 - could parameterize molecules without calculating their 3D coordinates

Against:
 - not enough use cases for coord-less (pun not intended) molsetups to justify the risk of API user mistakes when molsetup and coords can be manipulated separately
 - the positions of CG/G pseudo atom and generally offsite atoms depend on the positions of other atoms, even though this already partially mitigated because calculating the positions of offsite atoms is a two step process and the first step does not depend on coordinates.

**Comment by diogomart** [comment]
One more argument in favor of separation. Consider re-scoring a set of positions (a trajectory) and varying the parameterization of offsite partial charges. The distance between the offsite charge and the real atom would change. It is more comfortable to store the positions of real atoms only in the trajectory, and calculate the position of the offsite charges at runtime.
