### ISSUE TITLE
Clean up examples directory

### ISSUE THREAD

**Issue by diogomart** [forlilab/Meeko#195]
We should probably remove some of the stuff if it's not essential, make sure the stuff that we keep is up to date, and check for duplication with the recently written tutorials.

**Comment by rwxayheee** [comment]
Hi @diogomart 
Currently in example we have: 
├── BACE_macrocycle
├── autodock_zn
├── chorizo
├── covalent_docking
├── cyclodextrin_flexible
├── dihedrals-from-openff
├── hydrated_docking
├── reactive_adgpu
└── writer_example


The Colab examples are different from these. Do you want me to complete the listed examples? I’m a bit unfamiliar with the systems, but I can learn. The problem with the reactive and covalent docking was no PDB ID was given. For covalent docking it can be guessed from the pdb file. For reactive docking there isn’t enough information. Because of that I didn’t use these systems. 

If given about 1-2 more weeks I can complete these examples and write the traditional step-by-step tutorials. What do you think? We can talk when we meet today

**Comment by diogomart** [comment]
Just to have a record here: we agreed to delete the entire thing as the recent tutorials do not make any use of it.

**Comment by diogomart** [comment]
Entire example folder removed in #199
