### ISSUE TITLE
Atom type definition maybe not correct for "CCNN=NC"

### ISSUE THREAD

**Issue by rongfengzou** [forlilab/Meeko#240]
Atom type definition not correct for "CCNN=NC"

here's what I get using mk_prepare_ligand.py

REMARK SMILES CCNN=NC
REMARK SMILES IDX 3 1 2 3 1 4 4 5 5 6 6 7
REMARK H PARENT 3 2
REMARK Flexibility Score: inf
ROOT
ATOM      1  N   UNL     1       3.181  -0.927  -1.048  1.00  0.00    -0.292 NA
ATOM      2  H   UNL     1       2.615  -1.587  -1.572  1.00  0.00     0.185 HD
ENDROOT
BRANCH   1   3
ATOM      3  C   UNL     1       2.637   0.015  -0.108  1.00  0.00     0.133 C
ATOM      4  C   UNL     1       2.429  -0.584   1.269  1.00  0.00     0.029 C
ENDBRANCH   1   3
BRANCH   1   5
ATOM      5  N   UNL     1       4.509  -1.093  -1.138  1.00  0.00    -0.080 NA
ATOM      6  N   UNL     1       4.739  -1.979  -1.980  1.00  0.00    -0.175 NA
ATOM      7  C   UNL     1       6.178  -2.172  -2.171  1.00  0.00     0.200 C
ENDBRANCH   1   5
TORSDOF 2

The atomtype for the first N seems to be "N", not 'NA'...

**Comment by lattaai8** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the AtomTyper class to correctly assign 'N' atom type to non-aromatic, 3-connected nitrogens that were previously assigned 'NA'. This addresses the issue with the first nitrogen in CCNN=NC being incorrectly typed as 'NA'.

You can review changes in this commit: https://github.com/lattaai8/forlilab-Meeko-240/commit/33b3a1038271711993aa47360ad16017d5764b80.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by diogomart** [comment]
Good question. I think you are right. Gonna check that the triazene has a preference to be planar in DFT, like an aniline, and if yes will change it's type to N.

**Comment by diogomart** [comment]
The torsion profile showed a strong preference towards planarity, #242 types these as N instead of NA

**Comment by diogomart** [comment]
Implemented, will go out on v0.6.1. Thanks @rongfengzou
