### ISSUE TITLE
Quick question with mk_copy_coord.py

### ISSUE THREAD

**Issue by KSUN63** [forlilab/Meeko#35]
Hi there,

I really enjoyed meeko for its compatibility with the ad4-gpu docking result. However, when I installed the most recent version of meeko, I saw that putting in the original sdf file to facilitate the result conversion is not recommended. Can I know why that is the case?

The reason for me to ask about it is that I am trying to build a docking workflow that involves first converting sdf to pdbqt using meeko and then convert it back sdf once docking is complete. To give you more context, I have encountered some bond order issues with pdbqt file before, and that's why I would like to put in a reference sdf file for its final conversion from dlg to sdf to just make sure that I am recovering all the correct bond orders.

Thank you for your time,
Oliver

**Comment by diogomart** [comment]
Hi,

The template file is no longer necessary since v0.3 because the SMILES string in the PDBQT remark replaces the template file. This is easier to use because it's no longer necessary to keep the original SDFs around for converting from PDBQT/DLG to SDF. We are thinking about removing the template feature, that's why it's not recommended.

**Comment by KSUN63** [comment]
Thanks Diogo! That's really helpful and I will close this issue now :)
