### ISSUE TITLE
Macrocycles don't close if CG/G distance beyond cutoff (issue in Vina)

### ISSUE THREAD

**Issue by daoquangtung2411** [forlilab/Meeko#67]
Dear diogomart,

I'm currently docking several macrocycles.

Some of small rings-macrocycles is good after cross-docking but macrocycles with large rings does not have appropriate pose and scoree after docking. Here's the cross-docking results with 3 macrocycles
![IMG_4566](https://github.com/forlilab/Meeko/assets/78310750/60028491-5cc9-4336-97c4-3179061d2cfc)

I've read about flexible macrocycles docking but the result was really bad.

Here I attached the image of docking pose, chemical structure and code for docking. 
<img width="509" alt="Screenshot 2023-08-29 at 11 55 09" src="https://github.com/forlilab/Meeko/assets/78310750/7b90416e-b9a1-4f27-8672-bcd26dcb65e4">
<img width="473" alt="Screenshot 2023-08-29 at 11 53 55" src="https://github.com/forlilab/Meeko/assets/78310750/d6a0a9b9-3aab-4adf-9057-21bfce8690ea">
[docking_code.txt](https://github.com/forlilab/Meeko/files/12460439/docking_code.txt)

Can you look at it and provide me some solutions. 

Thanks in advanced.

**Comment by diogomart** [comment]
We set the cutoff to 20 Angstrom for the interactions involving the pseudo-atoms that restore the bond. Could you confirm that the very long bond is longer than 20 Angstrom?

**Comment by daoquangtung2411** [comment]
Hi, thanks for your respond.

As you can see from the result, the two pseudo atoms is very far from each other. The distance is 19.4 A (calculated by pymol)

<img width="540" alt="Screenshot 2023-08-31 at 15 35 22" src="https://github.com/forlilab/Meeko/assets/78310750/b733f3b4-47b5-4788-9054-cea47295295a">


Can you explain further about cutoff length for interaction involving pseudo-atoms. 
And also one more problem, the result after processed with mk_export.py has non-polar hydrogens.

Thank you very much

**Comment by diogomart** [comment]
Non-polar hydrogens are expected because `mk_export.py` adds hydrogens using RDKit's `Chem.AddHs(mol, addCoords=True)`

The potential to restore the bond increases linearly with distance, but after the cutoff (20 Angstroms) it is zero. The easiest short term solution is to recompile Vina and set the cutoff to a larger value. A better long term solution would be to use that term directly without precalculating it, so no cutoff is used, but I don't think we will implement that anytime soon.

That cutoff is set here on line 52, and also `m_max_cutoff` below on line 56 needs to be increased to the same value. I'd suggest 40 or 50 angstrom to be "safe". 
https://github.com/ccsb-scripps/AutoDock-Vina/blob/develop/src/lib/scoring_function.h#L52
Vina might be a little slower and use more memory, but honestly I don't know how significant this change in performance can be.

You'd change the code and re-compile locally: https://autodock-vina.readthedocs.io/en/latest/installation.html#building-from-source
(note that compiling for Python is a separate step)

**Comment by daoquangtung2411** [comment]
Yes, thank you very much
